### ISSUE TITLE
merge is not working with lww-set

### ISSUE THREAD

**Issue by bmabir17** [anshulahuja98/python3-crdt#6]
**package version 1.0.3**

I was testing lww-set with the following code
```python
from py3crdt.lww import LWWElementSet
lSet1 = LWWElementSet(id=1)
lSet2 = LWWElementSet(id=2)

lSet1.add('a')
lSet1.add('b')
lSet1.display()

lSet2.add('c')
lSet2.add('b')
lSet2.display()

lSet1.merge(lSet2)
lSet1.display()
```
**The output is:**
```
A: a:390933, b:390965, 
R: 
A: c:391324, b:391360, 
R: 
A: a:390933, b:390965, c:391324, b:391360, 
R: 
```
**Expected Result:**
The merge function should have only kept one instance of the `b` element. But there is a duplicate.
Or did I misunderstood the concept of LWW-set?

**Comment by anshulahuja98** [comment]
Thanks for reaching out @bmabir17 
@geetesh-gupta can you investigate this.

**Comment by geetesh-gupta** [comment]
@bmabir17 Thanks for pointing out the problem. 
You are definitely correct regarding the duplicate instance of element `b`.

Currently, the `merge` function is not filtering based on timestamp.
I'll fix it and update the code.

**Comment by bmabir17** [comment]
@geetesh-gupta Thank you for taking a look at it.
